# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_id', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='Creation date')),
                ('position', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('Object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trollo.Object')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('List_id', models.IntegerField(default=0)),
                ('Object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trollo.Object')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='Object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trollo.Object'),
        ),
        migrations.AddField(
            model_name='element',
            name='Object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trollo.Object'),
        ),
    ]
