# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trollo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Project_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='element',
            name='Task_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='list',
            name='project_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='object',
            name='position',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='List_id',
            field=models.IntegerField(default=1),
        ),
    ]
