# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trollo', '0002_auto_20170604_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='List_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='element',
            name='Project_id',
            field=models.IntegerField(default=1),
        ),
    ]
